# Generated by Django 4.2.4 on 2023-08-27 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categorias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="descripcion"),
                ),
                ("marca", models.CharField(max_length=100, verbose_name="marca")),
                ("slug", models.CharField(max_length=200)),
                (
                    "images",
                    models.ImageField(upload_to="productos", verbose_name="images"),
                ),
                ("precio", models.IntegerField(max_length=10, verbose_name="precio")),
                ("stock", models.IntegerField(max_length=10, verbose_name="stock")),
                ("is_available", models.BooleanField(default=True)),
                ("create", models.DateTimeField(auto_now_add=True)),
                ("cambio", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categorias.categoria",
                    ),
                ),
            ],
            options={"verbose_name": "nombre", "verbose_name_plural": "nombres",},
        ),
    ]
